WebAuthn and Simulator detection
otpless-tech/Otpless-iOS-SDK pull request #29
Opened 2024-08-01 09:44 UTC by sparsh-otpless

2024-08-01 09:57 UTC, digvijay-otpless commented on Example/OtplessSDK/LoggerVC.swift
> +    var headerLabel: UILabel = {
initialize the headerLabel in `setupHeaderLabel` method same as it is getting done for `tableView`.

2024-08-01 10:04 UTC, digvijay-otpless commented on OtplessSDK/Classes/DeviceInfoUtils.swift
> +        #if swift(>=4.1)
shorten the code
 #if swift(>=4.1)
            return targetEnvironment(simulator)
        #else
           return (arch(i386) || arch(x86_64)) && os(iOS)
        #endif

2024-08-12 07:47 UTC, dev-otpless-tech requested changes

2024-08-12 07:47 UTC, dev-otpless-tech commented on OtplessSDK/Classes/OtplessView.swift
> +                    OtplessLogger.log(string: request.url?.absoluteString ?? "Unable to get URL", type: "WebView URL")
Remove this for release scheme

2024-08-12 07:47 UTC, dev-otpless-tech commented on OtplessSDK/Classes/OtplessWebAuthnManagerImpl.swift
> +class OtplessWebAuthnManagerImpl: NSObject, OtplessWebAuthnManager, ASAuthorizationControllerDelegate, ASAuthorizationControllerPresentationContextProviding {
Can we move to extenstions of Otplesswebauthn

2024-08-12 07:47 UTC, dev-otpless-tech commented on OtplessSDK/Classes/OtplessWebAuthnManager.swift
> +//  OtplessWebAuthnManager.swift
not a manager make it Otplesswebauthn

2024-08-12 07:47 UTC, dev-otpless-tech commented on OtplessSDK/Classes/OtplessWebAuthnManagerImpl.swift
> +        if !isWindowValid() {
do the consideration analysis

2024-08-12 07:47 UTC, dev-otpless-tech commented on OtplessSDK/Classes/OtplessWebAuthnManagerImpl.swift
> +                authController.delegate = self
explore the all function which can lead to success and failure and utilize them accordingly for feedback

2024-08-12 07:47 UTC, dev-otpless-tech commented on OtplessSDK/Classes/OtplessWebAuthnManagerImpl.swift
> +                let authController = ASAuthorizationController(authorizationRequests: [ platformKeyRequest ])
Common this piece of code

2024-08-12 07:47 UTC, dev-otpless-tech commented on OtplessSDK/Classes/OtplessWebAuthnManagerImpl.swift
> +extension OtplessWebAuthnManagerImpl {
change the name

2024-08-12 07:47 UTC, dev-otpless-tech commented on OtplessSDK/Classes/OtplessWebListenerImpl.swift
> +class OtplessWebListenerImpl: OtplessWebListener {
do the changes as per discussion

2024-08-20 08:22 UTC, dev-otpless-tech approved these changes

2024-08-20 08:24 UTC, merged